---

version: '2'

services:
  tika:
    image: apache/tika:1.26
    network_mode: "host"

  elasticsearch:
    image: elasticsearch:7.12.1
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - cluster.routing.allocation.disk.threshold_enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    network_mode: "host"

  search:
    image: search:latest
    depends_on:
      - elasticsearch
    ports:
      - "9000:9000"
    network_mode: "host"
